module.exports = {
    prefix: "ras-",
    content: ["./src/**/*.{html,ts}"],
    theme: {
        extend: {
            height: {
                "full-vh": "100vh",
            },
            width: {
                "full-vw": "100vw",
            },
            backgroundColor: {
                common: "var(--commonBgColor)",
            },
            colors: {
                primary: {
                    default: "var(--primaryColor)",
                    100: "hsl(var(--primaryVar), 90%)",
                    200: "hsl(var(--primaryVar), 85%)",
                    300: "hsl(var(--primaryVar), 80%)",
                    400: "hsl(var(--primaryVar), 75%)",
                    500: "hsl(var(--primaryVar), 70%)",
                    600: "hsl(var(--primaryVar), 65%)",
                    800: "hsl(var(--primaryVar), 60%)",
                    900: "hsl(var(--primaryVar), 55%)",
                },
                secondary: {
                    default: "var(--secondaryColor)",
                    100: "hsl(var(--secondaryVar), 90%)",
                    200: "hsl(var(--secondaryVar), 80%)",
                    300: "hsl(var(--secondaryVar), 75%)",
                    400: "hsl(var(--secondaryVar), 70%)",
                    500: "hsl(var(--secondaryVar), 65%)",
                    600: "hsl(var(--secondaryVar), 60%)",
                    800: "hsl(var(--secondaryVar), 55%)",
                    900: "hsl(var(--secondaryVar), 50%)",
                },
                success: {
                    default: "var(--successColor)",
                    100: "hsl(var(--successVar), 90%)",
                    200: "hsl(var(--successVar), 80%)",
                    300: "hsl(var(--successVar), 75%)",
                    400: "hsl(var(--successVar), 70%)",
                    500: "hsl(var(--successVar), 65%)",
                    600: "hsl(var(--successVar), 60%)",
                    800: "hsl(var(--successVar), 55%)",
                    900: "hsl(var(--successVar), 50%)",
                },
                warning: {
                    default: "var(--warningColor)",
                    100: "hsl(var(--warningVar), 90%)",
                    200: "hsl(var(--warningVar), 80%)",
                    300: "hsl(var(--warningVar), 75%)",
                    400: "hsl(var(--warningVar), 70%)",
                    500: "hsl(var(--warningVar), 65%)",
                    600: "hsl(var(--warningVar), 60%)",
                    800: "hsl(var(--warningVar), 55%)",
                    900: "hsl(var(--warningVar), 50%)",
                },
                danger: {
                    default: "var(--dangerColor)",
                    100: "hsl(var(--dangerVar), 90%)",
                    200: "hsl(var(--dangerVar), 80%)",
                    300: "hsl(var(--dangerVar), 75%)",
                    400: "hsl(var(--dangerVar), 70%)",
                    500: "hsl(var(--dangerVar), 65%)",
                    600: "hsl(var(--dangerVar), 60%)",
                    800: "hsl(var(--dangerVar), 55%)",
                    900: "hsl(var(--dangerVar), 50%)",
                },
                info: {
                    default: "var(--infoColor)",
                    100: "hsl(var(--infoVar), 90%)",
                    200: "hsl(var(--infoVar), 80%)",
                    300: "hsl(var(--infoVar), 75%)",
                    400: "hsl(var(--infoVar), 70%)",
                    500: "hsl(var(--infoVar), 65%)",
                    600: "hsl(var(--infoVar), 60%)",
                    800: "hsl(var(--infoVar), 55%)",
                    900: "hsl(var(--infoVar), 50%)",
                },
                light: {
                    default: "var(--lightColor)",
                    100: "hsl(var(--lightVar), 95%)",
                    200: "hsl(var(--lightVar), 90%)",
                    300: "hsl(var(--lightVar), 85%)",
                    400: "hsl(var(--lightVar), 80%)",
                    500: "hsl(var(--lightVar), 75%)",
                    600: "hsl(var(--lightVar), 70%)",
                    800: "hsl(var(--lightVar), 65%)",
                    900: "hsl(var(--lightVar), 60%)",
                },
                dark: {
                    default: "var(--darkColor)",
                    100: "hsl(var(--darkVar), 45%)",
                    200: "hsl(var(--darkVar), 40%)",
                    300: "hsl(var(--darkVar), 35%)",
                    400: "hsl(var(--darkVar), 30%)",
                    500: "hsl(var(--darkVar), 25%)",
                    600: "hsl(var(--darkVar), 20%)",
                    800: "hsl(var(--darkVar), 15%)",
                    900: "hsl(var(--darkVar), 10%)",
                },
            },
        },
    },
    plugins: [],
};
